apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-deply
  name: my-deply
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-deply
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-deply
    spec:
      containers:
      - image: nginx:1.19.5
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
