apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-taint
  name: app-taint
spec:
  containers:
  - image: nginx
    name: app-taint
    resources: {}
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule    
  nodeSelector: 
    kubernetes.io/hostname: kmaster   
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
