apiVersion: v1
kind: Pod
metadata:
  name: constraints-cpu-memory
spec:
  containers:
  - name: constraints-cpu-memory
    image: nginx
    resources:
      limits:
        cpu: "600m"
      requests:
        cpu: "200m"
    resources:
      limits:
        memory: "800Mi"
      requests:
        memory: "500Mi"      
