apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
       
  volumes:
  - name: shared-volume
    emptyDir: {}

  containers:
  - image: nginx
    name: nginx1
    volumeMounts:
    - mountPath: /mountpoint-1
      name: shared-volume 
 
  - image: nginx
    name: nginx2
    volumeMounts:
    - mountPath: /mountpoint-2
      name: shared-volume

